services:
  microservice:
    container_name: microservice
    build: ./microservice
    volumes:
      - ./microservice/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3011:3011"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"

  gateway:
    container_name: apigateway
    build: ./apigateway
    volumes:
      - ./apigateway/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3010:3010"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"

  login_microservice:
    container_name: login_microservice
    build: ./login_microservice
    volumes:
      - ./login_microservice/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3012:3012"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"

networks:
  msexample:
    driver: bridge
