version:

services:
  apigateway:
    container_name: apigateway
    build: ./apigateway
    volumes:
      - ./apigateway/code:/app
    networks:
      - msexample
    ports:
      - "80:80"
    working_dir: /app
    command: npm start
    depends_on:
      - waterusage

  waterusage:
    container_name: waterusage
    build: ./waterusage
    volumes:
      - ./waterusage/code:/app
      - ./waterusage/db.json:/app/db.json
    networks:
      - msexample
    ports:
      - "3011:3011"
    working_dir: /app
    command: npm start

networks:
  msexample:
    driver: bridge
