version: '3.8'

services:

  gateway:
    container_name: apigateway
    build: ./apigateway
    volumes:
      - ./apigateway/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3010:3010"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"

  waterusage:
    container_name: waterusage
    build: ./waterusage
    volumes:
      - ./waterusage/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3011:3011"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"

  login_microservice:
    container_name: login_microservice
    build: ./login_microservice
    volumes:
      - ./login_microservice/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3012:3012"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"

  outfit_microservice:
    container_name: outfit_microservice
    build: ./outfit_microservice
    volumes:
      - ./outfit_microservice/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3013:3013"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"

networks:
  msexample:
    driver: bridge
